import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import ApperIcon from '@/components/ApperIcon';
import Button from '@/components/atoms/Button';
import { cn } from '@/utils/cn';

// Emoji name mappings for search functionality
const EMOJI_NAMES = {
  '😀': 'grinning face smile happy',
  '😃': 'grinning face big eyes smile happy',
  '😄': 'grinning face smiling eyes happy joy',
  '😁': 'beaming face smiling eyes grin happy',
  '😆': 'grinning squinting face laugh happy',
  '😅': 'grinning face sweat relieved happy',
  '🤣': 'rolling floor laughing rofl',
  '😂': 'face tears joy laugh crying',
  '🙂': 'slightly smiling face smile',
  '🙃': 'upside down face silly',
  '😉': 'winking face wink flirt',
  '😊': 'smiling face smiling eyes blush happy',
  '😇': 'smiling face halo angel innocent',
  '🥰': 'smiling face hearts love adore',
  '😍': 'smiling face heart eyes love crush',
  '🤩': 'star struck excited amazing wow',
  '😘': 'face blowing kiss love',
  '😗': 'kissing face kiss',
  '😚': 'kissing face closed eyes kiss',
  '😙': 'kissing face smiling eyes kiss',
  '🥲': 'smiling face tear emotional',
  '😋': 'face savoring food yummy delicious',
  '😛': 'face tongue silly playful',
  '😜': 'winking face tongue playful',
  '🤪': 'zany face crazy silly',
  '😝': 'squinting face tongue silly',
  '🤑': 'money mouth face rich dollar',
  '🤗': 'hugging face hug embrace',
  '🤭': 'face hand over mouth oops giggle',
  '🤫': 'shushing face quiet ssh silence',
  '🤔': 'thinking face hmm ponder',
  '😐': 'neutral face meh',
  '😑': 'expressionless face blank',
  '😶': 'face without mouth silent',
  '😏': 'smirking face smirk',
  '😒': 'unamused face unimpressed',
  '🙄': 'face rolling eyes whatever',
  '😬': 'grimacing face awkward oops',
  '😔': 'pensive face sad thoughtful',
  '😪': 'sleepy face tired yawn',
  '🤤': 'drooling face drool hungry',
  '😴': 'sleeping face sleep zzz',
  '😷': 'face medical mask sick',
  '🤒': 'face thermometer sick ill',
  '🤕': 'face head bandage hurt injured',
  '🤢': 'nauseated face sick gross',
  '🤮': 'face vomiting sick puke',
  '🤧': 'sneezing face achoo sick',
  '🥵': 'hot face sweat heat',
  '🥶': 'cold face freezing ice',
  '😵': 'dizzy face confused',
  '🤯': 'exploding head mind blown',
  '🤠': 'cowboy hat face western',
  '🥳': 'partying face party celebrate',
  '😎': 'smiling face sunglasses cool',
  '🤓': 'nerd face geek smart',
  '🧐': 'face monocle fancy',
  '😕': 'confused face puzzled',
  '😟': 'worried face concerned',
  '🙁': 'slightly frowning face sad',
  '☹️': 'frowning face sad unhappy',
  '😮': 'face open mouth shocked surprised',
  '😯': 'hushed face surprised',
  '😲': 'astonished face shocked',
  '😳': 'flushed face embarrassed',
  '🥺': 'pleading face puppy eyes beg',
  '😦': 'frowning face open mouth worried',
  '😧': 'anguished face distressed',
  '😨': 'fearful face scared afraid',
  '😰': 'anxious face sweat nervous',
  '😥': 'sad relieved face disappointed',
  '😢': 'crying face sad tears',
  '😭': 'loudly crying face bawling tears',
  '😱': 'face screaming fear shocked',
  '😖': 'confounded face frustrated',
  '😣': 'persevering face struggle',
  '😞': 'disappointed face sad',
  '😓': 'downcast face sweat sad',
  '😩': 'weary face tired exhausted',
  '😫': 'tired face exhausted',
  '🥱': 'yawning face sleepy tired',
  '😤': 'face steam nose triumph angry',
  '😡': 'pouting face angry mad',
  '😠': 'angry face mad furious',
  '🤬': 'face symbols cursing swearing',
  '😈': 'smiling face horns devil',
  '👿': 'angry face horns devil demon',
  '💀': 'skull death dead',
  '☠️': 'skull crossbones danger death',
  '💩': 'pile poo poop',
  '🤡': 'clown face circus',
  '👹': 'ogre monster demon',
  '👺': 'goblin monster',
  '👻': 'ghost boo spooky',
  '👽': 'alien extraterrestrial ufo',
  '👾': 'alien monster space invader',
  '🤖': 'robot face ai',
  '😺': 'grinning cat happy',
  '😸': 'grinning cat smiling eyes happy',
  '😹': 'cat tears joy laugh',
  '😻': 'smiling cat heart eyes love',
  '😼': 'cat wry smile smirk',
  '😽': 'kissing cat kiss',
  '🙀': 'weary cat shocked surprised',
  '😿': 'crying cat sad tears',
  '😾': 'pouting cat angry',
  '🐶': 'dog face puppy pet',
  '🐱': 'cat face kitten pet',
  '🐭': 'mouse face rodent',
  '🐹': 'hamster face pet',
  '🐰': 'rabbit face bunny',
  '🦊': 'fox face animal',
  '🐻': 'bear face animal',
  '🐼': 'panda face animal',
  '🐨': 'koala face animal',
  '🐯': 'tiger face animal',
  '🦁': 'lion face animal',
  '🐮': 'cow face animal moo',
  '🐷': 'pig face animal oink',
  '🐸': 'frog face animal',
  '🐵': 'monkey face animal',
  '🐔': 'chicken animal bird',
  '🐧': 'penguin bird animal',
  '🐦': 'bird animal',
  '🐤': 'baby chick bird',
  '🐣': 'hatching chick bird egg',
  '🐥': 'front facing baby chick bird',
  '🦆': 'duck bird animal',
  '🦅': 'eagle bird animal',
  '🦉': 'owl bird animal',
  '🦇': 'bat animal',
  '🐺': 'wolf face animal',
  '🐗': 'boar animal pig',
  '🐴': 'horse face animal',
  '🦄': 'unicorn face fantasy',
  '🐝': 'honeybee bee insect',
  '🐛': 'bug insect caterpillar',
  '🦋': 'butterfly insect',
  '🐌': 'snail slow',
  '🐞': 'lady beetle ladybug insect',
  '🐜': 'ant insect',
  '🐢': 'turtle animal slow',
  '🐍': 'snake animal reptile',
  '🦎': 'lizard reptile',
  '🐙': 'octopus animal sea',
  '🦑': 'squid animal sea',
  '🦐': 'shrimp animal seafood',
  '🦀': 'crab animal seafood',
  '🐡': 'blowfish pufferfish fish',
  '🐠': 'tropical fish animal',
  '🐟': 'fish animal',
  '🐬': 'dolphin animal sea',
  '🐳': 'spouting whale animal sea',
  '🐋': 'whale animal sea',
  '🦈': 'shark animal sea dangerous',
  '🐊': 'crocodile animal reptile',
  '🐅': 'tiger animal',
  '🐆': 'leopard animal',
  '🦓': 'zebra animal',
  '🦍': 'gorilla animal ape',
  '🐘': 'elephant animal',
  '🦛': 'hippopotamus animal',
  '🦏': 'rhinoceros animal',
  '🐪': 'camel animal desert',
  '🐫': 'two hump camel animal',
  '🦒': 'giraffe animal',
  '🐃': 'water buffalo animal',
  '🐂': 'ox animal',
  '🐄': 'cow animal',
  '🐎': 'horse animal racing',
  '🐖': 'pig animal',
  '🐏': 'ram animal sheep',
  '🐑': 'ewe sheep animal',
  '🐐': 'goat animal',
  '🦌': 'deer animal',
  '🐕': 'dog animal pet',
  '🐩': 'poodle dog animal',
  '🐈': 'cat animal pet',
  '🐓': 'rooster chicken bird',
  '🦃': 'turkey bird animal',
  '🕊️': 'dove bird peace',
  '🐇': 'rabbit animal bunny',
  '🐁': 'mouse animal rodent',
  '🐀': 'rat animal rodent',
  '🐿️': 'chipmunk squirrel animal',
  '🍇': 'grapes fruit food',
  '🍈': 'melon fruit food',
  '🍉': 'watermelon fruit food',
  '🍊': 'tangerine orange fruit food',
  '🍋': 'lemon fruit food sour',
  '🍌': 'banana fruit food',
  '🍍': 'pineapple fruit food',
  '🥭': 'mango fruit food',
  '🍎': 'red apple fruit food',
  '🍏': 'green apple fruit food',
  '🍐': 'pear fruit food',
  '🍑': 'peach fruit food',
  '🍒': 'cherries fruit food',
  '🍓': 'strawberry fruit food berry',
  '🥝': 'kiwi fruit food',
  '🍅': 'tomato vegetable food',
  '🥥': 'coconut fruit food',
  '🥑': 'avocado fruit food',
  '🍆': 'eggplant vegetable food',
  '🥔': 'potato vegetable food',
  '🥕': 'carrot vegetable food',
  '🌽': 'corn ear maize food',
  '🌶️': 'hot pepper spicy food',
  '🥒': 'cucumber vegetable food',
  '🥬': 'leafy green vegetables food',
  '🥦': 'broccoli vegetable food',
  '🍄': 'mushroom food',
  '🥜': 'peanuts food nuts',
  '🌰': 'chestnut food nut',
  '🍞': 'bread food loaf',
  '🥐': 'croissant bread food',
  '🥖': 'baguette bread food french',
  '🥨': 'pretzel food',
  '🥯': 'bagel food bread',
  '🥞': 'pancakes breakfast food',
  '🧇': 'waffle breakfast food',
  '🧀': 'cheese wedge food dairy',
  '🍖': 'meat bone food',
  '🍗': 'poultry leg chicken food',
  '🥩': 'cut meat steak food',
  '🥓': 'bacon food breakfast',
  '🍔': 'hamburger burger food',
  '🍟': 'french fries chips food',
  '🍕': 'pizza food slice',
  '🌭': 'hot dog food',
  '🥪': 'sandwich food',
  '🌮': 'taco mexican food',
  '🌯': 'burrito mexican food wrap',
  '🥙': 'stuffed flatbread food',
  '🥚': 'egg food breakfast',
  '🍳': 'cooking egg fried food',
  '🥘': 'shallow pan food cooking',
  '🍲': 'pot food stew',
  '🥣': 'bowl spoon food cereal',
  '🥗': 'green salad healthy food',
  '🍿': 'popcorn snack food',
  '🥫': 'canned food tin',
  '🍱': 'bento box japanese food',
  '🍘': 'rice cracker food',
  '🍙': 'rice ball onigiri food',
  '🍚': 'cooked rice food',
  '🍛': 'curry rice food',
  '🍜': 'steaming bowl noodles ramen food',
  '🍝': 'spaghetti pasta italian food',
  '🍠': 'roasted sweet potato food',
  '🍢': 'oden food japanese',
  '🍣': 'sushi food japanese',
  '🍤': 'fried shrimp tempura food',
  '🍥': 'fish cake swirl food',
  '🍡': 'dango food japanese',
  '🥮': 'moon cake food',
  '🥟': 'dumpling food',
  '🥠': 'fortune cookie food',
  '🥡': 'takeout box food chinese',
  '🍦': 'soft ice cream dessert',
  '🍧': 'shaved ice dessert',
  '🍨': 'ice cream dessert',
  '🍩': 'doughnut donut dessert',
  '🍪': 'cookie dessert',
  '🎂': 'birthday cake dessert celebration',
  '🍰': 'shortcake cake dessert',
  '🧁': 'cupcake dessert',
  '🥧': 'pie dessert',
  '🍫': 'chocolate bar dessert candy',
  '🍬': 'candy sweet dessert',
  '🍭': 'lollipop candy dessert',
  '🍮': 'custard pudding dessert',
  '🍯': 'honey pot sweet',
  '🍼': 'baby bottle milk',
  '🥛': 'glass milk dairy drink',
  '☕': 'hot beverage coffee tea drink',
  '🍵': 'teacup tea drink',
  '🍶': 'sake bottle cup drink',
  '🍺': 'beer mug drink alcohol',
  '🍻': 'clinking beer mugs cheers drink',
  '🥂': 'clinking glasses champagne toast',
  '🍷': 'wine glass drink alcohol',
  '🥃': 'tumbler glass whiskey drink',
  '🍸': 'cocktail glass drink martini',
  '🍹': 'tropical drink cocktail',
  '🍾': 'bottle popping cork champagne',
  '⚽': 'soccer ball football sport',
  '🏀': 'basketball sport ball',
  '🏈': 'american football sport',
  '⚾': 'baseball sport ball',
  '🎾': 'tennis sport ball',
  '🏐': 'volleyball sport ball',
  '🏉': 'rugby football sport',
  '🎱': 'pool 8 ball billiards',
  '🏓': 'ping pong table tennis',
  '🏸': 'badminton sport',
  '🥅': 'goal net sport',
  '🏹': 'bow arrow archery',
  '🎣': 'fishing pole fish',
  '🥊': 'boxing glove sport',
  '🥋': 'martial arts uniform karate',
  '🎽': 'running shirt sport',
  '🛹': 'skateboard sport',
  '🛼': 'roller skate sport',
  '⛸️': 'ice skate sport winter',
  '🥌': 'curling stone sport',
  '🎿': 'skis sport winter',
  '⛷️': 'skier sport winter',
  '🏂': 'snowboarder sport winter',
  '🏋️': 'person lifting weights gym',
  '🤸': 'person cartwheeling gymnastics',
  '⛹️': 'person bouncing ball basketball',
  '🏌️': 'person golfing golf',
  '🏇': 'horse racing jockey',
  '🧘': 'person lotus position yoga meditation',
  '🏊': 'person swimming sport',
  '🚣': 'person rowing boat',
  '🧗': 'person climbing sport',
  '🚵': 'person mountain biking cycling',
  '🚴': 'person biking cycling',
  '🏆': 'trophy win award champion',
  '🥇': 'first place medal gold winner',
  '🥈': 'second place medal silver',
  '🥉': 'third place medal bronze',
  '🏅': 'sports medal award',
  '🎖️': 'military medal honor',
  '🎗️': 'reminder ribbon awareness',
  '🎫': 'ticket admission event',
  '🎟️': 'admission tickets event',
  '🎪': 'circus tent entertainment',
  '🎭': 'performing arts theater drama',
  '🎨': 'artist palette paint art',
  '🎬': 'clapper board movie film',
  '🎤': 'microphone sing music',
  '🎧': 'headphone music listen',
  '🎼': 'musical score music',
  '🎹': 'musical keyboard piano',
  '🥁': 'drum drumsticks music',
  '🎷': 'saxophone music jazz',
  '🎺': 'trumpet music',
  '🎸': 'guitar music rock',
  '🎻': 'violin music classical',
  '🎲': 'game die dice random',
  '🎯': 'direct hit target bullseye',
  '🎳': 'bowling sport',
  '🎮': 'video game controller gaming',
  '🎰': 'slot machine gambling casino',
  '🧩': 'puzzle piece jigsaw',
  '🚗': 'automobile car vehicle',
  '🚕': 'taxi cab vehicle',
  '🚙': 'sport utility vehicle suv car',
  '🚌': 'bus vehicle',
  '🚎': 'trolleybus vehicle',
  '🏎️': 'racing car fast',
  '🚓': 'police car cop vehicle',
  '🚑': 'ambulance emergency vehicle',
  '🚒': 'fire engine truck vehicle',
  '🚐': 'minibus van vehicle',
  '🚚': 'delivery truck vehicle',
  '🚛': 'articulated lorry truck vehicle',
  '🚜': 'tractor farm vehicle',
  '🚲': 'bicycle bike',
  '🛵': 'motor scooter bike',
  '🏍️': 'motorcycle bike',
  '🚨': 'police car light siren emergency',
  '🚔': 'oncoming police car cop',
  '🚍': 'oncoming bus vehicle',
  '🚘': 'oncoming automobile car',
  '🚖': 'oncoming taxi cab',
  '🚡': 'aerial tramway cable car',
  '🚠': 'mountain cableway cable car',
  '🚟': 'suspension railway train',
  '🚃': 'railway car train',
  '🚋': 'tram car streetcar',
  '🚞': 'mountain railway train',
  '🚝': 'monorail train',
  '🚄': 'high speed train bullet',
  '🚅': 'bullet train shinkansen',
  '🚈': 'light rail train',
  '🚂': 'locomotive steam train',
  '🚆': 'train railway',
  '🚇': 'metro subway train',
  '🚊': 'tram streetcar',
  '🚉': 'station train railway',
  '✈️': 'airplane plane flight',
  '🛫': 'airplane departure takeoff',
  '🛬': 'airplane arrival landing',
  '🛩️': 'small airplane plane',
  '💺': 'seat chair airplane',
  '🚁': 'helicopter chopper',
  '🛶': 'canoe boat',
  '⛵': 'sailboat boat',
  '🚤': 'speedboat boat fast',
  '🛥️': 'motor boat',
  '🛳️': 'passenger ship cruise',
  '⛴️': 'ferry boat',
  '🚢': 'ship boat',
  '⚓': 'anchor ship boat',
  '🚧': 'construction sign warning',
  '🚦': 'vertical traffic light signal',
  '🚥': 'horizontal traffic light signal',
  '🚏': 'bus stop sign',
  '🗺️': 'world map travel',
  '🗿': 'moai statue easter island',
  '🗽': 'statue liberty new york',
  '🗼': 'tokyo tower japan',
  '🏰': 'castle building',
  '🏯': 'japanese castle building',
  '🏟️': 'stadium sports arena',
  '🎡': 'ferris wheel carnival',
  '🎢': 'roller coaster thrill ride',
  '🎠': 'carousel horse merry go round',
  '⛲': 'fountain water',
  '⛱️': 'umbrella ground beach',
  '🏖️': 'beach umbrella vacation',
  '🏝️': 'desert island vacation',
  '🏜️': 'desert hot dry',
  '🌋': 'volcano mountain',
  '⛰️': 'mountain peak',
  '🏔️': 'snow capped mountain peak',
  '🗻': 'mount fuji japan',
  '🏕️': 'camping tent outdoor',
  '⛺': 'tent camping',
  '🏠': 'house building home',
  '🏡': 'house garden home',
  '🏘️': 'houses buildings neighborhood',
  '🏚️': 'derelict house building abandoned',
  '🏗️': 'building construction crane',
  '🏭': 'factory industrial building',
  '🏢': 'office building work',
  '🏬': 'department store shopping',
  '🏣': 'japanese post office',
  '🏤': 'post office mail',
  '🏥': 'hospital medical building',
  '🏦': 'bank money building',
  '🏨': 'hotel building accommodation',
  '🏪': 'convenience store shop',
  '🏫': 'school building education',
  '🏩': 'love hotel building',
  '💒': 'wedding church chapel',
  '🏛️': 'classical building museum',
  '⛪': 'church building religion',
  '🕌': 'mosque building islam',
  '🕍': 'synagogue building judaism',
  '🛕': 'hindu temple building',
  '🌅': 'sunrise morning',
  '🌄': 'sunrise mountains morning',
  '🌠': 'shooting star wish',
  '🎇': 'sparkler fireworks',
  '🎆': 'fireworks celebration',
  '🌇': 'sunset evening',
  '🌆': 'cityscape dusk evening',
  '🏙️': 'cityscape buildings urban',
  '🌃': 'night stars city',
  '🌌': 'milky way galaxy stars',
  '🌉': 'bridge night',
  '🌁': 'foggy weather',
  '⌚': 'watch time',
  '📱': 'mobile phone smartphone',
  '📲': 'mobile phone arrow call',
  '💻': 'laptop computer',
  '⌨️': 'keyboard typing',
  '🖥️': 'desktop computer',
  '🖨️': 'printer print',
  '🖱️': 'computer mouse click',
  '🕹️': 'joystick gaming',
  '💾': 'floppy disk save',
  '💿': 'optical disk cd',
  '📀': 'dvd disk',
  '📼': 'videocassette vhs tape',
  '📷': 'camera photo',
  '📸': 'camera flash photo',
  '📹': 'video camera film',
  '🎥': 'movie camera film',
  '📽️': 'film projector movie',
  '📞': 'telephone receiver phone call',
  '☎️': 'telephone phone',
  '📟': 'pager beeper',
  '📠': 'fax machine',
  '📺': 'television tv',
  '📻': 'radio music',
  '🎙️': 'studio microphone podcast',
  '⏱️': 'stopwatch timer',
  '⏲️': 'timer clock countdown',
  '⏰': 'alarm clock wake',
  '🕰️': 'mantelpiece clock time',
  '⌛': 'hourglass done sand timer',
  '⏳': 'hourglass sand timer',
  '📡': 'satellite antenna signal',
  '🔋': 'battery power energy',
  '🔌': 'electric plug power',
  '💡': 'light bulb idea bright',
  '🔦': 'flashlight torch light',
  '🕯️': 'candle light flame',
  '💸': 'money wings fly cash',
  '💵': 'dollar banknote money cash',
  '💴': 'yen banknote money cash',
  '💶': 'euro banknote money cash',
  '💷': 'pound banknote money cash',
  '💰': 'money bag cash rich',
  '💳': 'credit card payment',
  '💎': 'gem stone diamond precious',
  '⚖️': 'balance scale justice law',
  '🔧': 'wrench tool fix',
  '🔨': 'hammer tool build',
  '⚒️': 'hammer pick tools',
  '🛠️': 'hammer wrench tools',
  '⛏️': 'pick tool mining',
  '🔩': 'nut bolt screw',
  '⚙️': 'gear settings mechanical',
  '⛓️': 'chains link metal',
  '🔫': 'water pistol toy gun',
  '💣': 'bomb explosion danger',
  '🔪': 'kitchen knife cut',
  '🗡️': 'dagger knife weapon',
  '⚔️': 'crossed swords fight',
  '🛡️': 'shield protection defend',
  '🔮': 'crystal ball fortune future',
  '💈': 'barber pole haircut',
  '🔭': 'telescope stars space',
  '🔬': 'microscope science lab',
  '💊': 'pill medicine drug',
  '💉': 'syringe injection needle',
  '🌡️': 'thermometer temperature',
  '🚽': 'toilet bathroom',
  '🚿': 'shower bath clean',
  '🛁': 'bathtub bath',
  '🧼': 'soap clean wash',
  '🧽': 'sponge clean',
  '🧴': 'lotion bottle cream',
  '🔑': 'key lock unlock',
  '🗝️': 'old key vintage',
  '🚪': 'door entrance exit',
  '🛋️': 'couch lamp furniture',
  '🛏️': 'bed sleep rest',
  '🛌': 'person bed sleeping',
  '🧸': 'teddy bear toy',
  '🖼️': 'framed picture art',
  '🎁': 'wrapped gift present',
  '🎈': 'balloon party celebration',
  '🎏': 'carp streamer fish flag',
  '🎀': 'ribbon bow present',
  '🎊': 'confetti ball party celebration',
  '🎉': 'party popper celebration',
  '🎎': 'japanese dolls festival',
  '🏮': 'red paper lantern japanese',
  '✉️': 'envelope letter mail',
  '📩': 'envelope arrow mail send',
  '📨': 'incoming envelope mail',
  '📧': 'e-mail email internet',
  '💌': 'love letter heart mail',
  '📥': 'inbox tray receive',
  '📤': 'outbox tray send',
  '📦': 'package box delivery',
  '🏷️': 'label tag price',
  '📪': 'closed mailbox lowered flag',
  '📫': 'closed mailbox raised flag',
  '📬': 'open mailbox raised flag',
  '📭': 'open mailbox lowered flag',
  '📮': 'postbox mail',
  '📯': 'postal horn mail',
  '📜': 'scroll document paper',
  '📃': 'page curl document',
  '📄': 'page document paper',
  '📑': 'bookmark tabs organize',
  '📊': 'bar chart graph statistics',
  '📈': 'chart increasing trending up',
  '📉': 'chart decreasing trending down',
  '📆': 'tear off calendar date',
  '📅': 'calendar date schedule',
  '📇': 'card index rolodex',
  '🗂️': 'card index dividers organize',
  '🗒️': 'spiral notepad notes',
  '🗓️': 'spiral calendar date',
  '📋': 'clipboard document',
  '📁': 'file folder organize',
  '📂': 'open file folder',
  '📰': 'newspaper news',
  '📓': 'notebook notes',
  '📔': 'notebook decorative cover',
  '📒': 'ledger notebook',
  '📕': 'closed book read',
  '📗': 'green book read',
  '📘': 'blue book read',
  '📙': 'orange book read',
  '📚': 'books stack read library',
  '📖': 'open book read',
  '🔖': 'bookmark mark page',
  '🔗': 'link chain connection',
  '📎': 'paperclip attach',
  '🖇️': 'linked paperclips attach',
  '📐': 'triangular ruler measure',
  '📏': 'straight ruler measure',
  '📌': 'pushpin pin tack',
  '📍': 'round pushpin pin location',
  '✂️': 'scissors cut',
  '🖊️': 'pen write',
  '🖋️': 'fountain pen write',
  '✒️': 'black nib pen write',
  '🖌️': 'paintbrush paint art',
  '🖍️': 'crayon draw color',
  '📝': 'memo pencil note write',
  '✏️': 'pencil write draw',
  '🔍': 'magnifying glass tilted left search',
  '🔎': 'magnifying glass tilted right search',
  '🔏': 'locked pen ink security',
  '🔐': 'locked key secure',
  '🔒': 'locked lock secure',
  '🔓': 'unlocked open lock',
  '❤️': 'red heart love',
  '🧡': 'orange heart love',
  '💛': 'yellow heart love',
  '💚': 'green heart love',
  '💙': 'blue heart love',
  '💜': 'purple heart love',
  '🖤': 'black heart love',
  '🤍': 'white heart love',
  '🤎': 'brown heart love',
  '💔': 'broken heart sad breakup',
  '❣️': 'heart exclamation love emphasis',
  '💕': 'two hearts love',
  '💞': 'revolving hearts love',
  '💓': 'beating heart love pulse',
  '💗': 'growing heart love',
  '💖': 'sparkling heart love',
  '💘': 'heart arrow cupid love',
  '💝': 'heart box gift love',
  '☮️': 'peace symbol',
  '✝️': 'latin cross christian',
  '☪️': 'star crescent islam',
  '🕉️': 'om hindu',
  '☸️': 'wheel dharma buddhism',
  '✡️': 'star david judaism',
  '🔯': 'dotted six pointed star',
  '🕎': 'menorah candelabrum jewish',
  '☯️': 'yin yang balance',
  '☦️': 'orthodox cross christian',
  '🛐': 'place worship religion',
  '♈': 'aries zodiac ram',
  '♉': 'taurus zodiac bull',
  '♊': 'gemini zodiac twins',
  '♋': 'cancer zodiac crab',
  '♌': 'leo zodiac lion',
  '♍': 'virgo zodiac maiden',
  '♎': 'libra zodiac scales',
  '♏': 'scorpio zodiac scorpion',
  '♐': 'sagittarius zodiac archer',
  '♑': 'capricorn zodiac goat',
  '♒': 'aquarius zodiac water bearer',
  '♓': 'pisces zodiac fish',
  '⛎': 'ophiuchus zodiac serpent bearer',
  '❌': 'cross mark x no',
  '⭕': 'hollow red circle o',
  '🛑': 'stop sign octagon',
  '⛔': 'no entry prohibition',
  '📛': 'name badge tag',
  '🚫': 'prohibited forbidden no',
  '💯': 'hundred points perfect score',
  '💢': 'anger symbol mad angry',
  '♨️': 'hot springs onsen steam',
  '🚷': 'no pedestrians prohibited',
  '🚯': 'no littering prohibited',
  '🚳': 'no bicycles prohibited',
  '🚱': 'non potable water prohibited',
  '🔞': 'no one under eighteen adult',
  '📵': 'no mobile phones prohibited',
  '🚭': 'no smoking prohibited',
  '❗': 'exclamation mark red important',
  '❕': 'white exclamation mark',
  '❓': 'question mark red',
  '❔': 'white question mark',
  '‼️': 'double exclamation mark',
  '⁉️': 'exclamation question mark',
  '⚠️': 'warning caution',
  '🚸': 'children crossing warning',
  '♻️': 'recycling symbol green eco',
  '✅': 'check mark button yes correct',
  '💹': 'chart increasing yen trending',
  '❇️': 'sparkle star',
  '✳️': 'eight spoked asterisk star',
  '❎': 'cross mark button no',
  '🌐': 'globe meridians world internet',
  '💠': 'diamond shape blue',
  'Ⓜ️': 'circled m metro',
  '🌀': 'cyclone spiral hurricane',
  '💤': 'zzz sleeping sleep',
  '🏧': 'atm sign bank money',
  '🚾': 'water closet wc restroom',
  '♿': 'wheelchair symbol accessible',
  '🅿️': 'p button parking',
  '🚹': 'mens room sign bathroom',
  '🚺': 'womens room sign bathroom',
  '🚼': 'baby symbol infant',
  '🚻': 'restroom bathroom wc',
  '🚮': 'litter bin symbol trash',
  '🎦': 'cinema movie theater',
  '📶': 'antenna bars signal',
  'ℹ️': 'information i',
  '🔤': 'input latin letters abc',
  '🔡': 'input latin lowercase',
  '🔠': 'input latin uppercase',
  '🆖': 'ng button no good',
  '🆗': 'ok button okay',
  '🆙': 'up button arrow',
  '🆒': 'cool button',
  '🆕': 'new button',
  '🆓': 'free button',
  '0️⃣': 'keycap digit zero number',
  '1️⃣': 'keycap digit one number',
  '2️⃣': 'keycap digit two number',
  '3️⃣': 'keycap digit three number',
  '4️⃣': 'keycap digit four number',
  '5️⃣': 'keycap digit five number',
  '6️⃣': 'keycap digit six number',
  '7️⃣': 'keycap digit seven number',
  '8️⃣': 'keycap digit eight number',
  '9️⃣': 'keycap digit nine number',
  '🔟': 'keycap ten number',
  '🔢': 'input numbers 1234',
  '#️⃣': 'keycap hash pound',
  '*️⃣': 'keycap asterisk star',
  '⏏️': 'eject button',
  '▶️': 'play button start',
  '⏸️': 'pause button stop',
  '⏯️': 'play pause button toggle',
  '⏹️': 'stop button',
  '⏺️': 'record button',
  '⏭️': 'next track button skip',
  '⏮️': 'last track button previous',
  '⏩': 'fast forward button',
  '⏪': 'fast reverse button rewind',
  '⏫': 'fast up button',
  '⏬': 'fast down button',
  '◀️': 'reverse button back',
  '🔼': 'upwards button arrow',
  '🔽': 'downwards button arrow',
  '➡️': 'right arrow direction',
  '⬅️': 'left arrow direction',
  '⬆️': 'up arrow direction',
  '⬇️': 'down arrow direction',
  '↗️': 'up right arrow diagonal',
  '↘️': 'down right arrow diagonal',
  '↙️': 'down left arrow diagonal',
  '↖️': 'up left arrow diagonal',
  '↕️': 'up down arrow vertical',
  '↔️': 'left right arrow horizontal',
  '↪️': 'left arrow curving right',
  '↩️': 'right arrow curving left',
  '⤴️': 'right arrow curving up',
  '⤵️': 'right arrow curving down',
  '🔀': 'shuffle tracks button random',
  '🔁': 'repeat button loop',
  '🔂': 'repeat single button loop',
  '🔄': 'counterclockwise arrows button refresh',
  '🔃': 'clockwise vertical arrows',
  '🎵': 'musical note music',
  '🎶': 'musical notes music',
  '➕': 'plus sign add',
  '➖': 'minus sign subtract',
  '➗': 'division sign divide',
  '✖️': 'multiplication sign times',
  '♾️': 'infinity forever endless',
  '💲': 'heavy dollar sign money',
  '💱': 'currency exchange money',
  '™️': 'trade mark trademark',
  '©️': 'copyright',
  '®️': 'registered trademark',
  '〰️': 'wavy dash',
  '➰': 'curly loop',
  '➿': 'double curly loop',
  '🔚': 'end arrow button',
  '🔙': 'back arrow button return',
  '🔛': 'on arrow button',
  '🔝': 'top arrow button up',
  '🔜': 'soon arrow button',
  '✔️': 'check mark yes correct',
  '☑️': 'check box mark yes',
  '🔘': 'radio button',
  '🔴': 'red circle',
  '🟠': 'orange circle',
  '🟡': 'yellow circle',
  '🟢': 'green circle',
  '🔵': 'blue circle',
  '🟣': 'purple circle',
  '⚫': 'black circle',
  '⚪': 'white circle',
  '🟤': 'brown circle',
  '🔺': 'red triangle pointed up',
  '🔻': 'red triangle pointed down',
  '🔸': 'small orange diamond',
  '🔹': 'small blue diamond',
  '🔶': 'large orange diamond',
  '🔷': 'large blue diamond',
  '🔳': 'white square button',
  '🔲': 'black square button',
  '▪️': 'black small square',
  '▫️': 'white small square',
  '◾': 'black medium small square',
  '◽': 'white medium small square',
  '◼️': 'black medium square',
  '◻️': 'white medium square',
  '🟥': 'red square',
  '🟧': 'orange square',
  '🟨': 'yellow square',
  '🟩': 'green square',
  '🟦': 'blue square',
  '🟪': 'purple square',
  '⬛': 'black large square',
  '⬜': 'white large square',
  '🟫': 'brown square',
  '🔈': 'speaker low volume sound',
  '🔇': 'muted speaker no sound',
  '🔉': 'speaker medium volume sound',
  '🔊': 'speaker high volume sound loud',
  '🔔': 'bell notification alert',
  '🔕': 'bell slash mute silent',
  '📣': 'megaphone announcement',
  '📢': 'loudspeaker announcement',
  '💬': 'speech balloon chat message',
  '💭': 'thought balloon thinking',
  '🗯️': 'right anger bubble angry',
  '♠️': 'spade suit card',
  '♣️': 'club suit card',
  '♥️': 'heart suit card',
  '♦️': 'diamond suit card',
  '🃏': 'joker card wild',
  '🎴': 'flower playing cards',
  '🀄': 'mahjong red dragon tile',
  '🏳️': 'white flag surrender',
  '🏴': 'black flag pirate',
  '🏴‍☠️': 'pirate flag skull crossbones',
  '🏁': 'chequered flag racing finish',
  '🚩': 'triangular flag post',
  '🏳️‍🌈': 'rainbow flag pride lgbtq',
  '🏳️‍⚧️': 'transgender flag pride',
  '🇺🇳': 'flag united nations',
};
const EMOJI_CATEGORIES = {
  smileys: {
    name: 'Smileys & Emotion',
    icon: 'Smile',
    emojis: ['😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂', '🙂', '🙃', '😉', '😊', '😇', '🥰', '😍', '🤩', '😘', '😗', '😚', '😙', '🥲', '😋', '😛', '😜', '🤪', '😝', '🤑', '🤗', '🤭', '🤫', '🤔', '🤐', '🤨', '😐', '😑', '😶', '😏', '😒', '🙄', '😬', '🤥', '😌', '😔', '😪', '🤤', '😴', '😷', '🤒', '🤕', '🤢', '🤮', '🤧', '🥵', '🥶', '😶‍🌫️', '🥴', '😵', '🤯', '🤠', '🥳', '😎', '🤓', '🧐', '😕', '😟', '🙁', '☹️', '😮', '😯', '😲', '😳', '🥺', '😦', '😧', '😨', '😰', '😥', '😢', '😭', '😱', '😖', '😣', '😞', '😓', '😩', '😫', '🥱', '😤', '😡', '😠', '🤬', '😈', '👿', '💀', '☠️', '💩', '🤡', '👹', '👺', '👻', '👽', '👾', '🤖', '😺', '😸', '😹', '😻', '😼', '😽', '🙀', '😿', '😾']
  },
  animals: {
    name: 'Animals & Nature',
    icon: 'Dog',
    emojis: ['🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐨', '🐯', '🦁', '🐮', '🐷', '🐽', '🐸', '🐵', '🙈', '🙉', '🙊', '🐒', '🐔', '🐧', '🐦', '🐤', '🐣', '🐥', '🦆', '🦅', '🦉', '🦇', '🐺', '🐗', '🐴', '🦄', '🐝', '🐛', '🦋', '🐌', '🐞', '🐜', '🦟', '🦗', '🕷️', '🦂', '🐢', '🐍', '🦎', '🦖', '🦕', '🐙', '🦑', '🦐', '🦞', '🦀', '🐡', '🐠', '🐟', '🐬', '🐳', '🐋', '🦈', '🐊', '🐅', '🐆', '🦓', '🦍', '🦧', '🐘', '🦛', '🦏', '🐪', '🐫', '🦒', '🦘', '🐃', '🐂', '🐄', '🐎', '🐖', '🐏', '🐑', '🦙', '🐐', '🦌', '🐕', '🐩', '🦮', '🐕‍🦺', '🐈', '🐈‍⬛', '🐓', '🦃', '🦚', '🦜', '🦢', '🦩', '🕊️', '🐇', '🦝', '🦨', '🦡', '🦦', '🦥', '🐁', '🐀', '🐿️', '🦔']
  },
  food: {
    name: 'Food & Drink',
    icon: 'Coffee',
    emojis: ['🍇', '🍈', '🍉', '🍊', '🍋', '🍌', '🍍', '🥭', '🍎', '🍏', '🍐', '🍑', '🍒', '🍓', '🥝', '🍅', '🥥', '🥑', '🍆', '🥔', '🥕', '🌽', '🌶️', '🥒', '🥬', '🥦', '🧄', '🧅', '🍄', '🥜', '🌰', '🍞', '🥐', '🥖', '🥨', '🥯', '🥞', '🧇', '🧀', '🍖', '🍗', '🥩', '🥓', '🍔', '🍟', '🍕', '🌭', '🥪', '🌮', '🌯', '🥙', '🧆', '🥚', '🍳', '🥘', '🍲', '🥣', '🥗', '🍿', '🧈', '🧂', '🥫', '🍱', '🍘', '🍙', '🍚', '🍛', '🍜', '🍝', '🍠', '🍢', '🍣', '🍤', '🍥', '🥮', '🍡', '🥟', '🥠', '🥡', '🦀', '🦞', '🦐', '🦑', '🦪', '🍦', '🍧', '🍨', '🍩', '🍪', '🎂', '🍰', '🧁', '🥧', '🍫', '🍬', '🍭', '🍮', '🍯', '🍼', '🥛', '☕', '🍵', '🧃', '🥤', '🍶', '🍺', '🍻', '🥂', '🍷', '🥃', '🍸', '🍹', '🧉', '🍾', '🧊']
  },
  activities: {
    name: 'Activities',
    icon: 'Gamepad2',
    emojis: ['⚽', '🏀', '🏈', '⚾', '🥎', '🎾', '🏐', '🏉', '🥏', '🎱', '🪀', '🏓', '🏸', '🏒', '🏑', '🥍', '🏏', '🥅', '⛳', '🪁', '🏹', '🎣', '🤿', '🥊', '🥋', '🎽', '🛹', '🛼', '🛷', '⛸️', '🥌', '🎿', '⛷️', '🏂', '🪂', '🏋️', '🤼', '🤸', '🤺', '⛹️', '🤾', '🏌️', '🏇', '🧘', '🏊', '🤽', '🚣', '🧗', '🚵', '🚴', '🏆', '🥇', '🥈', '🥉', '🏅', '🎖️', '🏵️', '🎗️', '🎫', '🎟️', '🎪', '🤹', '🎭', '🩰', '🎨', '🎬', '🎤', '🎧', '🎼', '🎹', '🥁', '🎷', '🎺', '🎸', '🪕', '🎻', '🎲', '♟️', '🎯', '🎳', '🎮', '🎰', '🧩']
  },
  travel: {
    name: 'Travel & Places',
    icon: 'Plane',
    emojis: ['🚗', '🚕', '🚙', '🚌', '🚎', '🏎️', '🚓', '🚑', '🚒', '🚐', '🛻', '🚚', '🚛', '🚜', '🦯', '🦽', '🦼', '🛴', '🚲', '🛵', '🏍️', '🛺', '🚨', '🚔', '🚍', '🚘', '🚖', '🚡', '🚠', '🚟', '🚃', '🚋', '🚞', '🚝', '🚄', '🚅', '🚈', '🚂', '🚆', '🚇', '🚊', '🚉', '✈️', '🛫', '🛬', '🛩️', '💺', '🛰️', '🚀', '🛸', '🚁', '🛶', '⛵', '🚤', '🛥️', '🛳️', '⛴️', '🚢', '⚓', '⛽', '🚧', '🚦', '🚥', '🚏', '🗺️', '🗿', '🗽', '🗼', '🏰', '🏯', '🏟️', '🎡', '🎢', '🎠', '⛲', '⛱️', '🏖️', '🏝️', '🏜️', '🌋', '⛰️', '🏔️', '🗻', '🏕️', '⛺', '🛖', '🏠', '🏡', '🏘️', '🏚️', '🏗️', '🏭', '🏢', '🏬', '🏣', '🏤', '🏥', '🏦', '🏨', '🏪', '🏫', '🏩', '💒', '🏛️', '⛪', '🕌', '🕍', '🛕', '🕋', '⛩️', '🛤️', '🛣️', '🗾', '🎑', '🏞️', '🌅', '🌄', '🌠', '🎇', '🎆', '🌇', '🌆', '🏙️', '🌃', '🌌', '🌉', '🌁']
  },
  objects: {
    name: 'Objects',
    icon: 'Lightbulb',
    emojis: ['⌚', '📱', '📲', '💻', '⌨️', '🖥️', '🖨️', '🖱️', '🖲️', '🕹️', '🗜️', '💾', '💿', '📀', '📼', '📷', '📸', '📹', '🎥', '📽️', '🎞️', '📞', '☎️', '📟', '📠', '📺', '📻', '🎙️', '🎚️', '🎛️', '🧭', '⏱️', '⏲️', '⏰', '🕰️', '⌛', '⏳', '📡', '🔋', '🔌', '💡', '🔦', '🕯️', '🪔', '🧯', '🛢️', '💸', '💵', '💴', '💶', '💷', '💰', '💳', '💎', '⚖️', '🧰', '🔧', '🔨', '⚒️', '🛠️', '⛏️', '🔩', '⚙️', '🧱', '⛓️', '🧲', '🔫', '💣', '🧨', '🪓', '🔪', '🗡️', '⚔️', '🛡️', '🚬', '⚰️', '⚱️', '🏺', '🔮', '📿', '🧿', '💈', '⚗️', '🔭', '🔬', '🕳️', '🩹', '🩺', '💊', '💉', '🩸', '🧬', '🦠', '🧫', '🧪', '🌡️', '🧹', '🧺', '🧻', '🚽', '🚰', '🚿', '🛁', '🛀', '🧼', '🪒', '🧽', '🧴', '🛎️', '🔑', '🗝️', '🚪', '🪑', '🛋️', '🛏️', '🛌', '🧸', '🖼️', '🛍️', '🛒', '🎁', '🎈', '🎏', '🎀', '🎊', '🎉', '🎎', '🏮', '🎐', '🧧', '✉️', '📩', '📨', '📧', '💌', '📥', '📤', '📦', '🏷️', '📪', '📫', '📬', '📭', '📮', '📯', '📜', '📃', '📄', '📑', '🧾', '📊', '📈', '📉', '🗒️', '🗓️', '📆', '📅', '🗑️', '📇', '🗃️', '🗳️', '🗄️', '📋', '📁', '📂', '🗂️', '🗞️', '📰', '📓', '📔', '📒', '📕', '📗', '📘', '📙', '📚', '📖', '🔖', '🧷', '🔗', '📎', '🖇️', '📐', '📏', '🧮', '📌', '📍', '✂️', '🖊️', '🖋️', '✒️', '🖌️', '🖍️', '📝', '✏️', '🔍', '🔎', '🔏', '🔐', '🔒', '🔓']
  },
  symbols: {
    name: 'Symbols',
    icon: 'Hash',
    emojis: ['❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💔', '❣️', '💕', '💞', '💓', '💗', '💖', '💘', '💝', '💟', '☮️', '✝️', '☪️', '🕉️', '☸️', '✡️', '🔯', '🕎', '☯️', '☦️', '🛐', '⛎', '♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒', '♓', '🆔', '⚛️', '🉑', '☢️', '☣️', '📴', '📳', '🈶', '🈚', '🈸', '🈺', '🈷️', '✴️', '🆚', '💮', '🉐', '㊙️', '㊗️', '🈴', '🈵', '🈹', '🈲', '🅰️', '🅱️', '🆎', '🆑', '🅾️', '🆘', '❌', '⭕', '🛑', '⛔', '📛', '🚫', '💯', '💢', '♨️', '🚷', '🚯', '🚳', '🚱', '🔞', '📵', '🚭', '❗', '❕', '❓', '❔', '‼️', '⁉️', '🔅', '🔆', '〽️', '⚠️', '🚸', '🔱', '⚜️', '🔰', '♻️', '✅', '🈯', '💹', '❇️', '✳️', '❎', '🌐', '💠', 'Ⓜ️', '🌀', '💤', '🏧', '🚾', '♿', '🅿️', '🈳', '🈂️', '🛂', '🛃', '🛄', '🛅', '🚹', '🚺', '🚼', '🚻', '🚮', '🎦', '📶', '🈁', '🔣', 'ℹ️', '🔤', '🔡', '🔠', '🆖', '🆗', '🆙', '🆒', '🆕', '🆓', '0️⃣', '1️⃣', '2️⃣', '3️⃣', '4️⃣', '5️⃣', '6️⃣', '7️⃣', '8️⃣', '9️⃣', '🔟', '🔢', '#️⃣', '*️⃣', '⏏️', '▶️', '⏸️', '⏯️', '⏹️', '⏺️', '⏭️', '⏮️', '⏩', '⏪', '⏫', '⏬', '◀️', '🔼', '🔽', '➡️', '⬅️', '⬆️', '⬇️', '↗️', '↘️', '↙️', '↖️', '↕️', '↔️', '↪️', '↩️', '⤴️', '⤵️', '🔀', '🔁', '🔂', '🔄', '🔃', '🎵', '🎶', '➕', '➖', '➗', '✖️', '♾️', '💲', '💱', '™️', '©️', '®️', '〰️', '➰', '➿', '🔚', '🔙', '🔛', '🔝', '🔜', '✔️', '☑️', '🔘', '🔴', '🟠', '🟡', '🟢', '🔵', '🟣', '⚫', '⚪', '🟤', '🔺', '🔻', '🔸', '🔹', '🔶', '🔷', '🔳', '🔲', '▪️', '▫️', '◾', '◽', '◼️', '◻️', '🟥', '🟧', '🟨', '🟩', '🟦', '🟪', '⬛', '⬜', '🟫', '🔈', '🔇', '🔉', '🔊', '🔔', '🔕', '📣', '📢', '👁️‍🗨️', '💬', '💭', '🗯️', '♠️', '♣️', '♥️', '♦️', '🃏', '🎴', '🀄', '🕐', '🕑', '🕒', '🕓', '🕔', '🕕', '🕖', '🕗', '🕘', '🕙', '🕚', '🕛', '🕜', '🕝', '🕞', '🕟', '🕠', '🕡', '🕢', '🕣', '🕤', '🕥', '🕦', '🕧']
  },
  flags: {
    name: 'Flags',
    icon: 'Flag',
    emojis: ['🏳️', '🏴', '🏴‍☠️', '🏁', '🚩', '🏳️‍🌈', '🏳️‍⚧️', '🇺🇳', '🇦🇫', '🇦🇽', '🇦🇱', '🇩🇿', '🇦🇸', '🇦🇩', '🇦🇴', '🇦🇮', '🇦🇶', '🇦🇬', '🇦🇷', '🇦🇲', '🇦🇼', '🇦🇺', '🇦🇹', '🇦🇿', '🇧🇸', '🇧🇭', '🇧🇩', '🇧🇧', '🇧🇾', '🇧🇪', '🇧🇿', '🇧🇯', '🇧🇲', '🇧🇹', '🇧🇴', '🇧🇦', '🇧🇼', '🇧🇷', '🇮🇴', '🇻🇬', '🇧🇳', '🇧🇬', '🇧🇫', '🇧🇮', '🇰🇭', '🇨🇲', '🇨🇦', '🇮🇨', '🇨🇻', '🇧🇶', '🇰🇾', '🇨🇫', '🇹🇩', '🇨🇱', '🇨🇳', '🇨🇽', '🇨🇨', '🇨🇴', '🇰🇲', '🇨🇬', '🇨🇩', '🇨🇰', '🇨🇷', '🇨🇮', '🇭🇷', '🇨🇺', '🇨🇼', '🇨🇾', '🇨🇿', '🇩🇰', '🇩🇯', '🇩🇲', '🇩🇴', '🇪🇨', '🇪🇬', '🇸🇻', '🇬🇶', '🇪🇷', '🇪🇪', '🇸🇿', '🇪🇹', '🇪🇺', '🇫🇰', '🇫🇴', '🇫🇯', '🇫🇮', '🇫🇷', '🇬🇫', '🇵🇫', '🇹🇫', '🇬🇦', '🇬🇲', '🇬🇪', '🇩🇪', '🇬🇭', '🇬🇮', '🇬🇷', '🇬🇱', '🇬🇩', '🇬🇵', '🇬🇺', '🇬🇹', '🇬🇬', '🇬🇳', '🇬🇼', '🇬🇾', '🇭🇹', '🇭🇳', '🇭🇰', '🇭🇺', '🇮🇸', '🇮🇳', '🇮🇩', '🇮🇷', '🇮🇶', '🇮🇪', '🇮🇲', '🇮🇱', '🇮🇹', '🇯🇲', '🇯🇵', '🎌', '🇯🇪', '🇯🇴', '🇰🇿', '🇰🇪', '🇰🇮', '🇽🇰', '🇰🇼', '🇰🇬', '🇱🇦', '🇱🇻', '🇱🇧', '🇱🇸', '🇱🇷', '🇱🇾', '🇱🇮', '🇱🇹', '🇱🇺', '🇲🇴', '🇲🇬', '🇲🇼', '🇲🇾', '🇲🇻', '🇲🇱', '🇲🇹', '🇲🇭', '🇲🇶', '🇲🇷', '🇲🇺', '🇾🇹', '🇲🇽', '🇫🇲', '🇲🇩', '🇲🇨', '🇲🇳', '🇲🇪', '🇲🇸', '🇲🇦', '🇲🇿', '🇲🇲', '🇳🇦', '🇳🇷', '🇳🇵', '🇳🇱', '🇳🇨', '🇳🇿', '🇳🇮', '🇳🇪', '🇳🇬', '🇳🇺', '🇳🇫', '🇰🇵', '🇲🇰', '🇲🇵', '🇳🇴', '🇴🇲', '🇵🇰', '🇵🇼', '🇵🇸', '🇵🇦', '🇵🇬', '🇵🇾', '🇵🇪', '🇵🇭', '🇵🇳', '🇵🇱', '🇵🇹', '🇵🇷', '🇶🇦', '🇷🇪', '🇷🇴', '🇷🇺', '🇷🇼', '🇼🇸', '🇸🇲', '🇸🇹', '🇸🇦', '🇸🇳', '🇷🇸', '🇸🇨', '🇸🇱', '🇸🇬', '🇸🇽', '🇸🇰', '🇸🇮', '🇬🇸', '🇸🇧', '🇸🇴', '🇿🇦', '🇰🇷', '🇸🇸', '🇪🇸', '🇱🇰', '🇧🇱', '🇸🇭', '🇰🇳', '🇱🇨', '🇵🇲', '🇻🇨', '🇸🇩', '🇸🇷', '🇸🇪', '🇨🇭', '🇸🇾', '🇹🇼', '🇹🇯', '🇹🇿', '🇹🇭', '🇹🇱', '🇹🇬', '🇹🇰', '🇹🇴', '🇹🇹', '🇹🇳', '🇹🇷', '🇹🇲', '🇹🇨', '🇹🇻', '🇻🇮', '🇺🇬', '🇺🇦', '🇦🇪', '🇬🇧', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', '🏴󠁧󠁢󠁷󠁬󠁳󠁿', '🇺🇸', '🇺🇾', '🇺🇿', '🇻🇺', '🇻🇦', '🇻🇪', '🇻🇳', '🇼🇫', '🇪🇭', '🇾🇪', '🇿🇲', '🇿🇼']
  }
};

function EmojiPicker({ onEmojiSelect, onClose }) {
  const [activeCategory, setActiveCategory] = useState('smileys');
  const [searchQuery, setSearchQuery] = useState('');
  const pickerRef = useRef(null);

  useEffect(() => {
    function handleClickOutside(event) {
      if (pickerRef.current && !pickerRef.current.contains(event.target)) {
        onClose?.();
      }
    }

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [onClose]);

const filteredEmojis = searchQuery
    ? Object.values(EMOJI_CATEGORIES)
        .flatMap(cat => cat.emojis)
        .filter(emoji => {
          const searchLower = searchQuery.toLowerCase();
          const emojiName = EMOJI_NAMES[emoji] || '';
          return emojiName.includes(searchLower);
        })
    : EMOJI_CATEGORIES[activeCategory]?.emojis || [];

  const handleEmojiClick = (emoji) => {
    onEmojiSelect?.(emoji);
    onClose?.();
  };

  return (
    <motion.div
      ref={pickerRef}
      initial={{ opacity: 0, scale: 0.95, y: 10 }}
      animate={{ opacity: 1, scale: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95, y: 10 }}
      transition={{ duration: 0.15 }}
      className="absolute bottom-full right-0 mb-2 w-80 bg-white rounded-xl shadow-lg border border-gray-200 overflow-hidden z-50"
    >
      {/* Search Bar */}
      <div className="p-3 border-b border-gray-200">
        <div className="relative">
          <ApperIcon
            name="Search"
            size={16}
            className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"
          />
          <input
            type="text"
            placeholder="Search emoji..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary"
          />
        </div>
      </div>

      {/* Category Tabs */}
      {!searchQuery && (
        <div className="flex gap-1 p-2 border-b border-gray-200 overflow-x-auto">
          {Object.entries(EMOJI_CATEGORIES).map(([key, category]) => (
            <button
              key={key}
              onClick={() => setActiveCategory(key)}
              className={cn(
                "flex-shrink-0 p-2 rounded-lg transition-colors",
                activeCategory === key
                  ? "bg-primary/10 text-primary"
                  : "text-gray-600 hover:bg-gray-100"
              )}
              title={category.name}
            >
              <ApperIcon name={category.icon} size={20} />
            </button>
          ))}
        </div>
      )}

      {/* Emoji Grid */}
      <div className="h-64 overflow-y-auto p-2">
        <div className="grid grid-cols-8 gap-1">
          {filteredEmojis.map((emoji, index) => (
            <button
              key={`${emoji}-${index}`}
              onClick={() => handleEmojiClick(emoji)}
              className="w-full aspect-square flex items-center justify-center text-2xl hover:bg-gray-100 rounded-lg transition-colors active:scale-95"
              style={{ minWidth: '44px', minHeight: '44px' }}
            >
              {emoji}
            </button>
          ))}
        </div>
        {filteredEmojis.length === 0 && (
          <div className="flex flex-col items-center justify-center h-full text-gray-400">
            <ApperIcon name="Search" size={32} className="mb-2" />
            <p className="text-sm">No emojis found</p>
          </div>
        )}
      </div>
    </motion.div>
  );
}

export default EmojiPicker;